spring.application.name=ecommerce
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
app.jwt.secret=${JWT_SECRET}
app.jwt.issuer=ecommerce
app.jwt.ttl-seconds=900
app.frete.valor-padrao=15.00
