-- Esquema inicial. Tambem evolui o banco legado que tinha apenas usuario e produto.
CREATE TABLE IF NOT EXISTS usuario (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    senha varchar(255) NOT NULL,
    papel varchar(255)
);
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS papel varchar(255);
UPDATE usuario SET papel = 'CLIENTE' WHERE papel IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_usuario_email ON usuario (email);

CREATE TABLE IF NOT EXISTS categoria (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(255) NOT NULL,
    slug varchar(255) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_categoria_slug ON categoria (slug);

CREATE TABLE IF NOT EXISTS produto (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(255) NOT NULL,
    descricao varchar(4000),
    preco numeric(38,2),
    estoque integer NOT NULL,
    categoria_id bigint,
    tipo varchar(255),
    sku varchar(64),
    peso_gramas integer,
    altura_cm integer,
    largura_cm integer,
    comprimento_cm integer
);
ALTER TABLE produto ALTER COLUMN descricao TYPE varchar(4000);
ALTER TABLE produto ADD COLUMN IF NOT EXISTS categoria_id bigint;
ALTER TABLE produto ADD COLUMN IF NOT EXISTS tipo varchar(255);
ALTER TABLE produto ADD COLUMN IF NOT EXISTS sku varchar(64);
ALTER TABLE produto ADD COLUMN IF NOT EXISTS peso_gramas integer;
ALTER TABLE produto ADD COLUMN IF NOT EXISTS altura_cm integer;
ALTER TABLE produto ADD COLUMN IF NOT EXISTS largura_cm integer;
ALTER TABLE produto ADD COLUMN IF NOT EXISTS comprimento_cm integer;
UPDATE produto SET tipo = 'FISICO' WHERE tipo IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_produto_sku ON produto (sku);
ALTER TABLE produto ADD CONSTRAINT produto_categoria_fk FOREIGN KEY (categoria_id) REFERENCES categoria(id);

CREATE TABLE IF NOT EXISTS produto_imagens (
    produto_id bigint NOT NULL REFERENCES produto(id),
    ordem integer NOT NULL,
    url varchar(2048),
    PRIMARY KEY (produto_id, ordem),
    CONSTRAINT produto_imagens_ordem_check CHECK (ordem >= 0)
);
CREATE TABLE IF NOT EXISTS produto_atributos (
    produto_id bigint NOT NULL REFERENCES produto(id),
    chave varchar(60) NOT NULL,
    valor varchar(255),
    PRIMARY KEY (produto_id, chave)
);

CREATE TABLE IF NOT EXISTS carrinho_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id bigint NOT NULL REFERENCES usuario(id),
    produto_id bigint NOT NULL REFERENCES produto(id),
    quantidade integer NOT NULL,
    UNIQUE (usuario_id, produto_id),
    CONSTRAINT carrinho_quantidade_check CHECK (quantidade BETWEEN 1 AND 999)
);

CREATE TABLE IF NOT EXISTS faixa_frete (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cep_inicio varchar(255),
    cep_fim varchar(255),
    peso_minimo_gramas integer NOT NULL,
    peso_maximo_gramas integer NOT NULL,
    valor numeric(38,2)
);

CREATE TABLE IF NOT EXISTS pedido (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id bigint NOT NULL REFERENCES usuario(id),
    criado_em timestamp(6) with time zone,
    status varchar(255),
    estoque_reservado boolean NOT NULL DEFAULT false,
    idempotency_key varchar(80),
    checkout_session_id varchar(255),
    checkout_url varchar(2048),
    checkout_request_key varchar(255),
    pago_em timestamp(6) with time zone,
    subtotal numeric(38,2),
    frete numeric(38,2),
    total numeric(38,2),
    cep varchar(255),
    logradouro varchar(255),
    numero varchar(255),
    complemento varchar(255),
    bairro varchar(255),
    cidade varchar(255),
    uf varchar(255),
    UNIQUE (usuario_id, idempotency_key)
);
CREATE INDEX IF NOT EXISTS ix_pedido_usuario_criado ON pedido (usuario_id, criado_em DESC);
CREATE INDEX IF NOT EXISTS ix_pedido_expiracao ON pedido (status, criado_em) WHERE checkout_session_id IS NULL;

CREATE TABLE IF NOT EXISTS pedido_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id bigint NOT NULL REFERENCES pedido(id),
    produto_id bigint,
    nome varchar(255),
    sku varchar(255),
    tipo varchar(255),
    quantidade integer NOT NULL,
    preco_unitario numeric(38,2),
    subtotal numeric(38,2),
    arquivo_key varchar(255),
    arquivo_nome varchar(255)
);
CREATE INDEX IF NOT EXISTS ix_pedido_item_pedido ON pedido_item (pedido_id);

CREATE TABLE IF NOT EXISTS digital_arquivo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id bigint NOT NULL UNIQUE,
    chave varchar(255) NOT NULL,
    nome varchar(255) NOT NULL,
    enviado_em timestamp(6) with time zone
);

CREATE TABLE IF NOT EXISTS email_notificacao (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id bigint,
    status varchar(255),
    destinatario varchar(255),
    tentativas integer NOT NULL DEFAULT 0,
    proxima_tentativa timestamp(6) with time zone,
    enviado_em timestamp(6) with time zone,
    UNIQUE (pedido_id, status)
);
CREATE INDEX IF NOT EXISTS ix_email_notificacao_pendente
    ON email_notificacao (proxima_tentativa, id) WHERE enviado_em IS NULL;
