CREATE TABLE endereco_salvo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id bigint NOT NULL REFERENCES usuario(id),
    apelido varchar(40) NOT NULL,
    cep varchar(255),
    logradouro varchar(255),
    numero varchar(255),
    complemento varchar(255),
    bairro varchar(255),
    cidade varchar(255),
    uf varchar(255)
);
CREATE INDEX ix_endereco_salvo_usuario ON endereco_salvo (usuario_id);
