ALTER TABLE usuario ADD COLUMN senha_versao bigint NOT NULL DEFAULT 0;
CREATE TABLE recuperacao_senha (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id bigint NOT NULL REFERENCES usuario(id),
    token_hash varchar(64) NOT NULL UNIQUE,
    criado_em timestamp(6) with time zone NOT NULL,
    expira_em timestamp(6) with time zone NOT NULL,
    usado_em timestamp(6) with time zone
);
CREATE INDEX ix_recuperacao_senha_usuario ON recuperacao_senha (usuario_id);
ALTER TABLE email_notificacao ADD COLUMN recuperacao_url varchar(2048);
ALTER TABLE email_notificacao ADD COLUMN recuperacao_expira_em timestamp(6) with time zone;
